// <auto-generated />
namespace Rad301ClubsV1.Migrations.ClubModelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Clubinitialise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clubinitialise));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221112012_Club initialise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
